### ISSUE TITLE
Source type/webp and browser not compatible 

### ISSUE THREAD

**Issue by AndreaDelton** [ttc-freebies/plugin-responsive-images#147]
Local site on Xampp; Joomla 4.1.0, plugin enabled and tests both on Cassiopeia and other frameworks, with image.php override. I encountered this problem: if you choose to get the images also as Webp, the photos are not seen on IE11, and a webp version of the image is provided in <img>.
If you go back and delete only the choice of the Webp, with all browsers (IE, Edge, Chrome and Firefox), while clearing the cache, nothing changes, it continues to produce the source code of the type "image / webp" for all images, even for that of the <img> with a src = / media / cached-resp-images / images / demo / item-5_1920.jpg? version = cc22ed1e86 .., which however is a webp image, which browsers not compatible with Webp images cannot display. This is both in the blog category view and in the single article.

**Comment by dgrammatiko** [comment]
This is obviously a bug. Could you please test https://github.com/ttc-freebies/plugin-responsive-images/pull/148 ?

I will release an update the coming days

Thanks

**Comment by AndreaDelton** [comment]
I tried the new version of the Helper: unlike before, now the Webp source does not always appear, even if you only choose the JPG format.
For IE the image in <imc> is not displayed, even if it is in JPG format.
With all browsers, with the new Helper.php, the plugin creates the code with "source" only for the fulltext image and does not work with the intro_images in the "blog category" view (previously it reduced both types of images).
If you later choose to add the Webp format as well, nothing happens and I was able to get it only by disabling the plugin, deleting the cached-resp-images and then re-enabling the plugin.
Thank you.

**Comment by AndreaDelton** [comment]
Good evening, I hope to be able to contribute to the development of the
plugin by reporting the following, after updating the plugin with the
latest changes made by you and having repeated several tests (I have always
cleared the cache of the various browsers). Before the penultimate
modification of the Helper.php file, both the intro and the full images
were obtained with code <source>, in the article and blog view. After the
penultimate change, and even after the last ones, you get the <source> code
only of the full_image of the "article" view but nothing happens for the
intro_image images in the "blog" view.
Attention, using IE11 you do not see the full_image of the JPG type with
<source> code in the "article" view (you can see the intro_images in the
"blog" view because they are not modified). Plugin "Quality" options: if
you choose only JPG everything is fine, as if you choose to add the Webp
later. If you want to go back and choose JPG only, you still have the Webp
in the <source> code and the only solution is to delete all the
"cached-resp-images" folder.
Good job.

Il giorno mar 15 mar 2022 alle ore 00:57 Dimitris Grammatikogiannis <
***@***.***> ha scritto:

**Comment by AndreaDelton** [comment]
I add to the email sent yesterday the results of other tests performed
with a highlights module made by me and further tests with the Joomla
"Blog" view: I have chosen as breakpoint 768, 1200, 1600 and 1920; unlike
what was written yesterday, it also creates the right code for the
intro_image, but on condition that the intro_image of the article is bigger
than 768px. I have the intro_images in one of 768px (they will occupy a
maximum space of 600px on the devices) and none have been resized and the
code is not created in html, but if in the "image" folder I insert an
intro_image of 900px, then create the different images and generate the
html code. I confirm that after a change of options in the plugin (add the
Webp) the only solution is to delete the cached folder and not enough to
disable and re-enable the plugin.
I think it is essential to solve the problem of not displaying the JPG
version on IE11, since many still use that browser.
Thank you.

Il giorno mar 15 mar 2022 alle ore 20:02 Andrea Delton ***@***.***>
ha scritto:
