### ISSUE TITLE
add your plugin to mod_custom

### ISSUE THREAD

**Issue by nadjak77** [ttc-freebies/plugin-responsive-images#159]
Hi,
first of all: thank you for the great plugin! It works really great.
I have some images in mod_custom and want to use your plugin for this images, too.
So I add in your plugin:
component name:
component views: content,default
component database coluns: introtext,fulltext,text

But something is wrong. I think the component view is the wrong one. Can you help me?
Thanks 
Nadja

**Comment by dgrammatiko** [comment]
Can you share the layout that you're using for the mod_custom?

**Comment by nadjak77** [comment]
It is the default Layout from  joomla.
I just updated the site from joomla3 to joomla4

**Comment by dgrammatiko** [comment]
Ok here's an example (file responsive.php in your template/html/mod_custom):

```php
<?php
defined('_JEXEC') || die;

use Joomla\CMS\Layout\LayoutHelper;

$modId  = 'mod-custom' . $module->id;
$imgUrl = '';
$image  = '';
$attr   = '';
$imgUrl = $params->get('backgroundimage');

if ($imgUrl) {
	$image = LayoutHelper::render('joomla.html.image', [
		'src'      => $imgUrl,
		'alt'      => '',
		'loading'  => 'eager', // or 'lazy'
		'decoding' => 'async',
		'style'    => 'object-fit: cover; width: 100%; height: auto;',
	]);
}

echo '<div id="' . $modId . '" class="mod-custom custom" style="display:grid;">'
. '<div style="grid-column: 1 / -1; grid-row: 1 / -1;">' . $image . '</div>'
. '<div style="grid-column: 1 / -1; grid-row: 1 / -1; text-align:center; color:#fff; padding-top: 5rem;">' . $module->content . '</div>'
. '</div>';
```

Needs to be selected in the options of the module: 
<img width="1707" alt="Screenshot 2022-03-25 at 22 59 21" src="https://user-images.githubusercontent.com/3889375/160208173-d8f68e19-266c-4d8c-807b-fc1494464cf4.png">

And the result is:
<img width="1728" alt="Screenshot 2022-03-25 at 22 58 50" src="https://user-images.githubusercontent.com/3889375/160208190-97017e65-cdfa-4d6a-99cb-15eeacb2c2d5.png">


FWIW you need an actual image element tag and not a CSS background image...

I hope you get the idea...

**Comment by nadjak77** [comment]
Sorry, it still doesn't work.
In your plugin:
![grafik](https://user-images.githubusercontent.com/37655645/160344643-e962a11b-7a4b-4718-b7af-50684420dca6.png)

Layout in my modul:
![grafik](https://user-images.githubusercontent.com/37655645/160344765-d74c6ac3-6652-4607-a909-f2062f7fdb8b.png)

example page with the result:
https://www.spree-immobilien-beeskow.de/immobilien-tauche
all images are in modules

**Comment by dgrammatiko** [comment]
Make sure that your template has [this file](https://github.com/ttc-freebies/plugin-responsive-images/blob/4.0.0/src/package/image.php) in the `html/layouts/joomla/image.php`.

Also the image should not be inside the editor but rather in the image background
![Screenshot 2022-03-28 at 11 38 57](https://user-images.githubusercontent.com/3889375/160371078-f17e0adc-0cb8-425e-af5b-1fc718a22906.png)

![Screenshot 2022-03-28 at 11 39 17](https://user-images.githubusercontent.com/3889375/160371103-71367e43-110f-46eb-99ee-b677ca32252c.png)

**Comment by nadjak77** [comment]
sorry, it still doesn't work.
I added the standard and contetn to your plugin:
![grafik](https://user-images.githubusercontent.com/37655645/160371159-a08273df-f449-41d9-b67a-e7520526d556.png)
I added the image.php file to my template html/layouts/joomla/

I found something strange:
At the bottom of the site is a contact part with to images (a blue "ivd" logo and a yellow "DIA Zert" logo). The yellow one has your responsive option, the blue one not.
At the homepage the cards ove the contact part have your responsive options the other images on this site not. (all are in mod_custom)

I deleted the jommla and the browser cache.

**Comment by woluweb** [comment]
Hi @nadjak77 

I have just tested this successfully.
See https://dev.festivalmusiq3.be/responsive-banner

No need to change anything to the plugin parameters.
Just
- create the Alternate Layout (.php file) for Custom HTML Module
- create a Custom HTML Module
- add some text in the editor
- on the tab Options - select a "background image"
- on the tab Advanced, select the Layout you have just created

The Responsive Image plugin had indeed triggered as can be seen in the code : instead of my basic ìmg src="..."` I have the following
```html
<picture class="responsive-image"><source type="image/webp" sizes="(max-width: 1920px) 100vw 1920px" srcset="/media/cached-resp-images/images/banners/banner_992.webp?version=a655d66c1c2ccccce568a3226b574fcb 992w, /media/cached-resp-images/images/banners/banner_768.webp?version=a655d66c1c2ccccce568a3226b574fcb 768w, /media/cached-resp-images/images/banners/banner_480.webp?version=a655d66c1c2ccccce568a3226b574fcb 480w, /media/cached-resp-images/images/banners/banner_320.webp?version=a655d66c1c2ccccce568a3226b574fcb 320w, /media/cached-resp-images/images/banners/banner_200.webp?version=a655d66c1c2ccccce568a3226b574fcb 200w"><source type="image/jpeg" sizes="(max-width: 1920px) 100vw 1920px" srcset="/media/cached-resp-images/images/banners/banner_992.jpg?version=a655d66c1c2ccccce568a3226b574fcb 992w, /media/cached-resp-images/images/banners/banner_768.jpg?version=a655d66c1c2ccccce568a3226b574fcb 768w, /media/cached-resp-images/images/banners/banner_480.jpg?version=a655d66c1c2ccccce568a3226b574fcb 480w, /media/cached-resp-images/images/banners/banner_320.jpg?version=a655d66c1c2ccccce568a3226b574fcb 320w, /media/cached-resp-images/images/banners/banner_200.jpg?version=a655d66c1c2ccccce568a3226b574fcb 200w"><img loading="lazy" width="1140" height="600" src="/media/cached-resp-images/images/banners/banner_1920.jpg?version=a655d66c1c2ccccce568a3226b574fcb" alt="" decoding="async" style="object-fit: cover; width: 100%; height: auto;"></picture>
```

**Comment by nadjak77** [comment]
Ah! Thank you so much @woluweb . In the tab options "Inhalte vorbereiten" (I don't know the english text) was set to no. Switch to yes and it works.

**Comment by woluweb** [comment]
it is called "prepare content" (but in my case I think it does work whether or not "prepare content" is set to Yes)

**Comment by AndreaDelton** [comment]
I confirm that the plugin works very well even by not adding mod_custom and parameters in the plugin settings.
The problem remains that the plugin does not show images on Internet Explorer, as from attached photos.
The images would be seen if the plugin wrote the name of the site in the src of the img in JPG (in my test just add / helix before the / media / etc to see the photo). Could this fix be made?
![IE11 image issue](https://user-images.githubusercontent.com/100350887/162468960-d1a7df8b-8404-4734-8f33-4f8f5be420a9.jpg)
![IE11 visible IMG](https://user-images.githubusercontent.com/100350887/162468968-aaf6ef1e-dd30-4aff-994b-6aacdf2363b9.jpg)

**Comment by dgrammatiko** [comment]
> Could this fix be made?

Cay you try something for me (as it's hard atm to get an instance of IE locally):

in the IE console, find the image element and in the `src` attribute change the `?version=....` to `#...` (keeping the alphanumeric value just replace the `?version=` with a `#`). If that works I can add a patch this weekend

**Comment by AndreaDelton** [comment]
I have tried and unfortunately it still doesn't work, as you can see from the photo. I am available to make any other tests that you deem necessary. Thanks.

![IMG with #](https://user-images.githubusercontent.com/100350887/162482028-35f3fa55-def1-421c-8f5a-b4c71a79c67f.jpg)

**Comment by dgrammatiko** [comment]
@AndreaDelton there's some more information about IE not displaying images if there's no extension: https://answers.microsoft.com/en-us/ie/forum/all/some-jpeg-pictures-do-not-display-on-ie11-but/ccdb61db-8763-4804-9d12-cfb53dab7940

Basically, that's a security option that is totally wrong as the types of files on the internet are not supposed to be sniffed from the extension (but rather from the mime type that the server is sending). 
The hashed part of the image URL is a feature (is all about cache invalidation) and I'n not happy removing it. Also IE is officially dead in 2 months but regardless, probably you have elevated security rules which are expected to break some websites...

Just to add one more thing here: this could be also your local server (most likely, now that I read the messages on the link I posted above). You could try to see if this is still happening in a real Server (ie linux based and properly configured).

**Comment by AndreaDelton** [comment]
Thanks for your patience. I set IE security parameters to a minimum, but nothing has changed. At the moment I can't try an online production site, but I saw it has the same problem, with IE, the online site that Woluweb reported:

https://dev.festivalmusiq3.be/responsive-banner

Woluweb could tell us a little more. Anyway thanks.

**Comment by woluweb** [comment]
FYI: I tried to open the page with IE... but I discovered that clicking on the IE icon does not open IE anymore but Microsoft Edge actually.

**Comment by AndreaDelton** [comment]
Thanks Woluweb and Dimitris.
It is true that IE is dying but I assume that many will continue to use it for a while and I would like them to see the images too. So I went into the Helper.php and on line 171:
      'src="/media/cached-resp-images/' . $image['dirname'] . '/' . $image['filename'] .

if I add the site name (I don't know the exact parameter code to write for different site names), it also works on IE without changing anything else (es. ?version=):
 'src="/helix/media/cached-resp-images/' . $image['dirname'] . '/' . $image['filename'] .

I'm not sure it's the cleanest way to fix this, code-wise and for future updates. I ask Dimitris's opinion on this.

**Comment by dgrammatiko** [comment]
@AndreaDelton that is correct but you will also have to apply that patch for every update. As I said supporting IE is not something that I'm really interested at this point of time (weeks before even Microsoft bans it) and on top of that Joomla 4 itself is not supporting it so... 

Anyways there's a 4.1 beta, https://responsive-images.dgrammatiko.dev/downloads/index.html that should address the bug with the modules reported by @nadjak77

I'm gonna close this issue but if there are still issues with the modules you're welcome to reopen it. Thanks
