### ISSUE TITLE
plugin seems to not trigger on Images for the Smart Search Result Page

### ISSUE THREAD

**Issue by woluweb** [ttc-freebies/plugin-responsive-images#162]
See https://github.com/joomla/joomla-cms/pull/37450#issuecomment-1087285125

**Comment by dgrammatiko** [comment]
Just copying over the original issue

One thing that I was wondering though @dgrammatiko : the plugin Responsive Images works automatically a.o. for intro & full images, for images within the articles, even in Custom HTML Modules.
But why doesn't it trigger for the Smart Search Result Page?

Indeed I get
`<img src="/images/concerts/bw1.jpg" alt="L'Ombre de Saint-Saëns" width="2000" height="1334" loading="lazy">`
and not the full figure/picture element like on the Article page itself

```js
<figure class="item-image">
  <picture class="responsive-image">
    <source type="image/webp" sizes="(max-width: 1920px) 100vw 1920px" srcset="/media/cached-resp-images/images/concerts/bw1_1920.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 1920w, /media/cached-resp-images/images/concerts/bw1_1600.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 1600w, /media/cached-resp-images/images/concerts/bw1_1200.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 1200w, /media/cached-resp-images/images/concerts/bw1_992.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 992w, /media/cached-resp-images/images/concerts/bw1_768.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 768w, /media/cached-resp-images/images/concerts/bw1_480.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 480w, /media/cached-resp-images/images/concerts/bw1_320.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 320w, /media/cached-resp-images/images/concerts/bw1_200.webp?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 200w">
    <source type="image/jpeg" sizes="(max-width: 1920px) 100vw 1920px" srcset="/media/cached-resp-images/images/concerts/bw1_1920.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 1920w, /media/cached-resp-images/images/concerts/bw1_1600.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 1600w, /media/cached-resp-images/images/concerts/bw1_1200.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 1200w, /media/cached-resp-images/images/concerts/bw1_992.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 992w, /media/cached-resp-images/images/concerts/bw1_768.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 768w, /media/cached-resp-images/images/concerts/bw1_480.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 480w, /media/cached-resp-images/images/concerts/bw1_320.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 320w, /media/cached-resp-images/images/concerts/bw1_200.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730 200w">
    <img loading="lazy" width="2000" height="1334" src="/media/cached-resp-images/images/concerts/bw1_1920.jpg?version=22e1d71d7cb6fd0e9b7e14fad9ef7730" itemprop="image" alt="L'Ombre de Saint-Saëns">
  </picture>			
  <figcaption class="caption">© Leslie Artamonow</figcaption>
</figure>
```

**Comment by dgrammatiko** [comment]
@woluweb do you have an override in all your templates like `templateName/html/layouts/joomla/html/image.php`?

It's probably a missing override of the file `templateName/html/layouts/joomla/html/image.php`.
You can get an installer for the override [here](https://responsive-images.dgrammatiko.dev/create-template-overrides/index.html), just ender the name of your template and then install the plugin that is automatically created (the plugin will self uninstall and if you already have an override it will keep a backup).

<img width="1645" alt="Screenshot 2022-04-04 at 15 41 30" src="https://user-images.githubusercontent.com/3889375/161557189-530dd431-80b8-4fea-bedb-e984dcdf57e7.png">

**Comment by woluweb** [comment]
the file `image.php` was indeed present both 
- in the parent template `/templates/cassiopeia/html/layouts/joomla/html/image.php`
- as in the child template `/templates/cassiopeia_fm3/html/layouts/joomla/html/image.php`

But I noticed that there were 4 days of difference between the 2 files. When opening them, the content was slightly different.
So I uninstalled the Package 4.0.7
It did uninstall but it did not delete those two files (is it meant ?). So I renamed them manually in order to disable them.

I reinstalled then 4.0.7 and got the image.php in the parent and in the child Cassiopeia (latest version and identical in both folders. No clue how they could be different, maybe something wrong with the Update process?).

So far so good!

But still, as you can see on the following page, Responsive Image does not trigger :
`https://dev.festivalmusiq3.be/recherche?q=saens`

Or am I supposed to configure the Plugin (by adding the component com_finder with some configuration) ?

Note: I don't have any override of `default_result.php` (and the Joomla one is the 4.1.2 one with the fix for the 2 lines of future version 4.1.3).

**Comment by dgrammatiko** [comment]
@woluweb your site should be fine. I will try to have a release the coming days

**Comment by woluweb** [comment]
héhé, I see that it works now on the website after your intervention. Excellent! Txs :)

oh, btw: if you release a new version, 1 typo:
- Scalling => Scaling

3 questions about the plugin since we are busy 😅 :

1. JPG is by default 85%, webp 60% and avif 40%. It it because 60% & 40% are good enough? Or was it just an example?
2. on the Components tab, only com_content & mod_articles_category are configured. Still the plugin works automagically on mod_latest and com_finder. So is this tab some old stuff not necessary anymore?
3. when installing, it gets installed automatically on Cassiopeia and all its child templates it seems? But so
  - one should ideally create its child templates *before* installing Responsive Images?
  - does an update of the plugin adapt image.php also for all child templates?
  - the image.php file is not installed by default on 3rd party templates, right?

**Comment by dgrammatiko** [comment]
>  It it because 60% & 40% are good enough?

These are empirical values and should work fine for most images

> So is this tab some old stuff not necessary anymore?

I think I really need to explain what these options do, in a very short description the user can select the `textarea` fields that the plugin needs to look for images. The component and views are for narrowing the scope (efficiency/performance) and the  `Component Database Columns` the name of the database columns that hold the data (usually is the same as the actual field in the plugin $row, etc). Bottom line most things should work out of the box but if you install some 3rd party extension with some fiddling you can make that work also


> when installing, it gets installed automatically on Cassiopeia and all its child templates it seems?

Yes

> one should ideally create its child templates before installing Responsive Images?

Not necessarily you can also use: https://responsive-images.dgrammatiko.dev/create-template-overrides/index.html or copy the file manually

> does an update of the plugin adapt image.php also for all child templates?

Yes

> the image.php file is not installed by default on 3rd party templates, right?

Any site template will get the overrides (there's a backup of the old file if there's one there already...)

**Comment by dgrammatiko** [comment]
@woluweb I will close this as I think that everything is covered with 4.2.0. If not please feel free to reopen or create a new issue
