### ISSUE TITLE
Double slashes in URL

### ISSUE THREAD

**Issue by RickR2H** [ttc-freebies/plugin-responsive-images#182]
I noticed that the plugin generated double slashes in the URL's.

![Image001](https://user-images.githubusercontent.com/5610413/166655187-7e1f7814-7f3f-4306-a2ac-a597477b004c.jpg)

**Comment by dgrammatiko** [comment]
What version are you using?

**Comment by RickR2H** [comment]
Sorry, forgot to mention. The 4.1.0 Beta 1 release.

**Comment by dgrammatiko** [comment]
And server info, OS, php?

**Comment by RickR2H** [comment]
WAMP on Windows 10 / PHP 8.0.13

**Comment by dgrammatiko** [comment]
@RickR2H 4.1.0-beta-2 should fix it: https://responsive-images.dgrammatiko.dev/downloads/index.html, if not please reopen

**Comment by RickR2H** [comment]
Fix works! Thanks! FYI I had to uninstall the previous version to get it to work.
