### ISSUE TITLE
how can I delete the cache

### ISSUE THREAD

**Issue by nadjak77** [ttc-freebies/plugin-responsive-images#191]
I found some img who are really to large. So I resized theme to the right width and height.
But in your cache the old width and height is storaged. How can I delete the cache?
I renamed the folder in media/cached-resp/images/images but now I only see broken images.
Thanks.

**Comment by dgrammatiko** [comment]
> But in your cache the old width and height is storaged.

If you resized them using Joomla's Media Manager then the cached images are already replaced. If you did it manually you need to ssh to your server and delete them manually

**Comment by nadjak77** [comment]
Ah! I have to delete the hole cached-resp-images folder. I only deleted a subfolder.
Now it works.
Thank you

**Comment by dgrammatiko** [comment]
A button allowing to clear the saved source sets images will come with 4.2
