### ISSUE TITLE
Not working in module

### ISSUE THREAD

**Issue by impressionestudio** [ttc-freebies/plugin-responsive-images#21]
Hi, 

I have used the plugin successfully for manipulating the content images of an article and I noticed that it has a great impact in Google Page Speed especially when the content images are big and many.

But I tried twice (the second try after long time from the first in order to be sure) to use the code in my module according to the easy instructions but the returned images are an empty string.

**Comment by dgrammatiko** [comment]
@impressionestudio can you copy/paste the code you've used?

**Comment by impressionestudio** [comment]
The PHP code is: 

```
$image = '<img src="'.JURI::base().$temp->image_intro.'" alt="'.$temp->image_intro_alt.'" />';
if (JPluginHelper::isEnabled('content', 'responsive')) 
{
	JLoader::register('Ttc\Freebies\Responsive\Helper', JPATH_ROOT . '/plugins/content/responsive/helper.php', true);
	$helper = new \Ttc\Freebies\Responsive\Helper;
	$image = $helper->transformImage($image, array(200, 320, 480, 768, 992, 1200, 1600, 1920));
}
echo $image;
```

The image tag without using your code is: 
`<img src="https://www.kalamatamediterraneanvillas.gr/images/destinations/kalamata-1-intro.jpg" data-src="https://www.kalamatamediterraneanvillas.gr/images/destinations/kalamata-1-intro.jpg" class=" jch-lazyloaded" alt="">`

Notice that the image url is full and not relative.

**Comment by dgrammatiko** [comment]
So I went over the code and you're right it expects a relative URL. An easy work around for your example could be:
```php
$image = '<img src="'.$temp->image_intro.'" alt="'.$temp->image_intro_alt.'" />';
if (JPluginHelper::isEnabled('content', 'responsive')) 
{
	JLoader::register('Ttc\Freebies\Responsive\Helper', JPATH_ROOT . '/plugins/content/responsive/helper.php', true);
	$helper = new \Ttc\Freebies\Responsive\Helper;
	$image = $helper->transformImage($image, array(200, 320, 480, 768, 992, 1200, 1600, 1920));
}
echo $image;
```

or if the variable has already the full path:

```php
$image = '<img src="'.str_replace(\Joomla\CMS\Uri\Uri::base(), '', $temp->image_intro).'" alt="'.$temp->image_intro_alt.'" />';
if (JPluginHelper::isEnabled('content', 'responsive')) 
{
	JLoader::register('Ttc\Freebies\Responsive\Helper', JPATH_ROOT . '/plugins/content/responsive/helper.php', true);
	$helper = new \Ttc\Freebies\Responsive\Helper;
	$image = $helper->transformImage($image, array(200, 320, 480, 768, 992, 1200, 1600, 1920));
}
echo $image;
```

basically `str_replace(\Joomla\CMS\Uri\Uri::base(), '', $imageVariable)` will convert any (same host) absolute path to relative.

**Comment by impressionestudio** [comment]
Using the relative path solved the problem.
Thanks for the help.
