### ISSUE TITLE
PNG images with transparency get black background

### ISSUE THREAD

**Issue by impressionestudio** [ttc-freebies/plugin-responsive-images#22]
One more issue that I met.
When I use PNG images that have transparency then the resized images appear with black background.

**Comment by dgrammatiko** [comment]
This is a problem with the underlying Library that this plugin is using (https://github.com/joomla/joomla-cms/tree/staging/libraries/src/Image)...

**Comment by impressionestudio** [comment]
Ok, I added an issue for this library.

**Comment by impressionestudio** [comment]
And by the way. Why the images are saved in the "media" folder and not in the "cache" folder?
Saving the images in the "cache" folder makes it easier to clean the old images and refresh the updated images.

**Comment by dgrammatiko** [comment]
> Saving the images in the "cache" folder makes it easier to clean the old images and refresh the updated images.

The cache folder is wiped out on every update so it would be really counter productive if you had to recreate **all** the images because there was an unrelated update in some php files...

**Comment by SharkyKZ** [comment]
The issue is coming from here:

https://github.com/ttc-freebies/plugin-responsive-images/blob/ca1a1164e438aff9d5092514cd958667c089c8ef/src/helper.php#L207-L222

These should be constants, not strings.

**Comment by dgrammatiko** [comment]
Thanks @SharkyKZ I guess I should do a better code review before merging anything
