### ISSUE TITLE
Webp doesn't work

### ISSUE THREAD

**Issue by mediafoks** [ttc-freebies/plugin-responsive-images#257]
Joomla 4.1.5, plugin v. 4.1.1
The "Create WebP images" plugin settings are enabled, but the webp does not generate.
Source Code:
`<img src="/images/img.jpg">`
Out:
```
<picture class="responsive-image">
<source type="image/jpeg" sizes="(max-width: 1920px) 100vw 1920px" srcset="/media/cached-resp-images/images/img_480.jpg?version=4ccfcf3e135d7861f5722ef65349ba49 480w, 
/media/cached-resp-images/images/img_320.jpg?version=4ccfcf3e135d7861f5722ef65349ba49 320w">
<img decoding="async" height="384" width="576" loading="lazy" src="/media/cached-resp-images//images/img_1920.jpg?version=4ccfcf3e135d7861f5722ef65349ba49">
</picture>
```

**Comment by dgrammatiko** [comment]
@mediafoks could you please share the `PHP Information` part of your system info `administrator/index.php?option=com_admin&view=sysinfo` 

If you're using GD should be something like:
<img width="1144" alt="Screenshot 2022-08-03 at 11 39 32" src="https://user-images.githubusercontent.com/3889375/182577170-41a5ef40-6dfa-48d1-affa-c9168c9136fb.png">

Similar goes for imagick...

If your installation doesn't support WebP the plugin won't magically create WebP images (same goes for Avif). Both these formats are depending on the support of the graphics libraries

**Comment by mediafoks** [comment]
Thank you!
gd MP Support - enabled, but imagick ImageMagick supported formats - webp no.

**Comment by dgrammatiko** [comment]
> gd MP Support - enabled, but imagick ImageMagick supported formats - webp no.

The graphic library is automatically picked with priority to imagick:
https://github.com/ttc-freebies/ttc-common-library/blob/6ffce4341b96815da6a189a471a2a9158835f7e9/src/libraries/Ttc/src/Freebies/Responsive/Helper.php#L213-L217

Maybe you could ask your host provider for an update of imagick, the latest versions have also support for Avif which is a better format (mostly leaner files with less artefacts)
