### ISSUE TITLE
Webp format is not supported by Imagick installation

### ISSUE THREAD

**Issue by impressionestudio** [ttc-freebies/plugin-responsive-images#27]
I tested the new version 3.5.3 and one page crashed with the following message: "Webp format is not supported by Imagick installation".

**Comment by dgrammatiko** [comment]
> "Webp format is not supported by Imagick installation"

This is a probably a misconfiguration of your server (eg: it reports support for WebP but in reality it doesn't have all the needed dependencies). Is this localhost? What OS? What's you phpinfo?

**Comment by dgrammatiko** [comment]
Please try 3.5.4

**Comment by impressionestudio** [comment]
Ok, it works now. 
But I noticed that the PNG images with transparency are converted with black color in the transparent areas.

**Comment by dgrammatiko** [comment]
I have tested the png transparency with multiple files successfully. Could you provide me the file that is misbehaving?

**Comment by impressionestudio** [comment]
Ops sorry, I guess it was the cache. 
I had to clean cache and do hard reload a couple or times to load the images correctly.
So there is no problem. My fault.

**Comment by dgrammatiko** [comment]
Good news, please consider submitting a review: https://extensions.joomla.org/extension/responsive-content-images/

**Comment by impressionestudio** [comment]
Didn't know it was published in Joomla Extensions directory. I wrote a review but at the moment the confirmation is pending.
