### ISSUE TITLE
Should also be working on the home page (com_content.featured)

### ISSUE THREAD

**Issue by peterhulst** [ttc-freebies/plugin-responsive-images#30]
It is easy to make the plugin also working on the home page.

Just modify in responsive.php:

//  if ($context === 'com_content.article' || $context === 'com_content.category') {
to:
    if ($context === 'com_content.article' || $context === 'com_content.featured' || $context === 'com_content.category') {

and:
//  if ($context === 'com_content.article' && !empty($row->text)) {
to:
    if (($context === 'com_content.article' || $context === 'com_content.featured') && !empty($row->text)) {

regards,
Peter

**Comment by dgrammatiko** [comment]
This is interesting, will investigate and release a new version with this

**Comment by dgrammatiko** [comment]
@peterhulst the version 4 (only for Joomla 4 atm) implements this plus a convenient way to add any component/module. You can check it https://responsive-images.dgrammatiko.dev

Thanks
