### ISSUE TITLE
Intro image mod_articles_latest

### ISSUE THREAD

**Issue by bahman-gh858** [ttc-freebies/plugin-responsive-images#302]
Hi!

Thanks for great plugin.

I have template override, mod_articles_latest which displays the article intro image.
But the plugin donen't seem to work for those images. I have I have tried with different Component Views and Component Database Columns.

Thanks!

**Comment by Der-Lizzard** [comment]
> Hi!
> 
> Thanks for great plugin.
> 
> I have template override, mod_articles_latest which displays the article intro image. But the plugin donen't seem to work for those images. I have I have tried with different Component Views and Component Database Columns.
> 
> Thanks!

Work with template override for mod_articles_latest (intro_image), but not automatically. I have to integrate it by myself in the override-file. Testet with template shaper_helixultimate.

**Comment by bahman-gh858** [comment]
Der-Lizzard, what do you mean by "ntegrate it by myself"? Can you explain a little more.

**Comment by dgrammatiko** [comment]
@bahman-gh858 it would more helpful if you have shared your code. Anyways render you image like:

```php
// Instead of this
<?php echo '<img src="' . $imageURL .'" alt="' . htmlspecialchars($imageAlt, ENT_COMPAT, 'UTF-8') . '">'; ?>


// Use this:
<?php echo LayoutHelper::render('joomla.html.image', ['src' => imageURL, 'alt' => $imageAlt]); ?>

```

Read more here: https://magazine.joomla.org/all-issues/february-2022/new-image-convention-to-help-developers

**Comment by bahman-gh858** [comment]
Thanks dgrammatiko!
I am using this code, which is published on: 
 https://web-eau.net/en/development/joomla-overrides/tips-and-snippets-for-override

// Display the intro image of an article
	$article_images  = json_decode($item->images);
	$article_image   = '';
	$article_image_alt   = '';
	if(isset($article_images->image_intro) && !empty($article_images->image_intro)) {
		$article_image  = $article_images->image_intro;
		$article_image_alt  = $article_images->image_intro_alt;
	}?>  					
		
	<a href="/<?php echo $item->link; ?>">
		<img class="" src="/<?php echo $article_image; ?>" alt="<?php echo $article_image_alt; ?>" >
	</a>

**Comment by dgrammatiko** [comment]
Try this

```php
<?php

use Joomla\CMS\Layout\LayoutHelper;

$article_images  = json_decode($item->images);

echo '<a href="/' . $item->link . '">';
if (isset($article_images->image_intro) && !empty($article_images->image_intro)) {
  echo LayoutHelper::render('joomla.html.image', [
    'src'         => $article_images->image_intro,
    'alt'         => $article_images->image_intro_alt,
  ]);
}

echo '</a>';

```

**Comment by bahman-gh858** [comment]
Thanks! It worked.

Great support!

**Comment by dgrammatiko** [comment]
I'm closing this as the issue was resolved

**Comment by bahman-gh858** [comment]
I detected some problem with your cod  `echo '<a href="/' . $item->link . '">';` , grateful if you can explain.
- When clicking on the image, the article does not open. Instead of the full link https://mydomain.xxx/menu/myarticle, the link becomes https://menu/myarticle

**Comment by dgrammatiko** [comment]
Try changing this

```php
echo '<a href="/' . $item->link . '">';
```

to this

```php
echo '<a href="' . Uri::root() .  $item->link . '">';
```

But also add the required dependency at the top of the file (if it isn't already there) `use Joomla\CMS\Uri\Uri;`

**Comment by bahman-gh858** [comment]
thanks so much! 
You solved my problem! it works, but a double slash is added after domains name:
(https://mydomain.xxx//menu/myarticle)

Completion:
I removed the code. Something strange happened suddenly. 
When you click on the image, you will see that the link has changed from mydomain.xxx/menu/article to:
www.sumsel.mydomain.xxx//menu/article.

Very strange. Now i disable the plugins and want investigate my site before i use it again.
