### ISSUE TITLE
Double-Slash in img-Tag

### ISSUE THREAD

**Issue by Der-Lizzard** [ttc-freebies/plugin-responsive-images#304]
Hi dgrammatiko,

i've seen that there is a double-Slash // in the img-tag. Is it a bug or something wrong in my configuration of the plugin?

Output from a standard content (blog-content):

![dgrammatiko-double-slash](https://user-images.githubusercontent.com/115063400/194318099-ed428b4f-f9e4-40c7-bd0e-8524a405ce3e.JPG)

Tested with:

- Joomla 4.2.3
- Plugin Version 4.1.1
- Templates: Cassiopeia & shaper_helixultimate

**Comment by dgrammatiko** [comment]
Could you try 4.2.0: https://github.com/ttc-freebies/plugin-responsive-images/blob/580d56b8fa5c8e4349102bb8182ce61f2b7a2778/site/dist/pkg_responsive_4.2.0.zip

**Comment by Der-Lizzard** [comment]
Fixed with 4.2.0 - works fine!

Thx for the fast support
