### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#313]
Or maybe my understanding is wrong.
I'm expecting something like DJ-WebP plugin, which is working in principle but is now disabled.
I have a Joomla site with featured articles on the home page like a blog.
Articles are published using JCE Free Edition. There are no media resize, etc. options, so when an author uploads images, he/she is uploading images with full resolution. Photos are located in subfolders of '\images'.
HTML source reads:
`<img src="scheme://www.example.com/foo/bar.jpg" alt="bar" width="340" height="614" style="margin: 0px 40px 0px 0px; float: left;" loading="lazy" data-path="local-images:/foo/bar.jpg" />`

This plugin doesn't change HTML in the way I expect.
I'm using it with default settings:

- Component name: com_content
- Component views: article,category,featured
- Component Database Columns: introtext,fulltext,text

Do I need some overwrites?
Plugin version 4.1.1 
Joomla 4.2.3
Cache OFF (for testing purposes)
PHP 8.1
EDIT: I'm using child template of Cassiopeia.

**Comment by dgrammatiko** [comment]
JCE is using their own media manager which is not compatible with the Joomla one. The events that this plugin is listening are not compatible (and will never be) with the ones from JCE. Try uninstalling JCE and see if that was the problem

**Comment by dgrammatiko** [comment]
Also could you confirm that you have a file `templates/cassiopeia/html/layouts/joomla/html/image.php`
and the contents of that file are:

<details>
<summary>image.php</summary >

```php
<?php
/**
 * @copyright   (C) 2021 Dimitrios Grammatikogiannis
 * @license     GNU General Public License version 2 or later
 */

/**
 * Layout variables
 * -----------------
 * @var   array  $displayData  Array with all the given attributes for the image element.
 *                             Eg: src, class, alt, width, height, loading, decoding, style, data-*
 *                             Note: only the alt and src attributes are escaped by default!
 */

defined('_JEXEC') || die;

use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Plugin\PluginHelper;
use Joomla\Utilities\ArrayHelper;
use Ttc\Freebies\Responsive\Helper as ResponsiveHelper;

$breakpoints = [200, 320, 480, 768, 992, 1200, 1600, 1920];

// Handle the alt attribute
if (isset($displayData['alt'])) {
  if ($displayData['alt'] === false) {
    unset($displayData['alt']);
  } else {
    $displayData['alt'] = $this->escape($displayData['alt']);
  }
}
// Handle the breakpoins
if (isset($displayData['breakpoints'])) {
  if (is_array($displayData['breakpoints'])) {
    $breakpoints = $displayData['breakpoints'];
  }
  unset($displayData['breakpoints']);
}
// Handle the decoding attribute
if (empty($displayData['decoding'])) {
  $displayData['decoding'] = 'async';
}
// Handle the loading attribute
if (empty($displayData['loading'])) {
  $displayData['loading'] = 'lazy';
}

$img = '<img ' . ArrayHelper::toString($displayData) . '>';

// Respect the plugin state
if (PluginHelper::isEnabled('content', 'responsive')) {
  $img = (new ResponsiveHelper)->transformImage($img, $breakpoints);
}

echo $img;

```

</details>

**Comment by pl71** [comment]
Yes, I have this file there, also I have it in 'templates/cassiopeia_my_child_template/html/layouts/joomla/html/'
Both files are the same. They match your code above.
Re: your first post, I do prefer using JCE, but for the testing, I will uninstall it.

**Comment by dgrammatiko** [comment]
Is your site public? If so can you share the url?
Also there is version 4.2 available [here](https://github.com/ttc-freebies/plugin-responsive-images/blob/580d56b8fa5c8e4349102bb8182ce61f2b7a2778/site/dist/pkg_responsive_4.2.0.zip) (I need to finish the docs before publishing it)

**Comment by pl71** [comment]
https://www.chernorizets.com/
JCE is still installed there.

Published items:
- Content - Responsive Images - 4.1.1
- Select Media-action - Responsive Images
- pkg_responsive

 I'm experimenting with a local version running on XAMPP for Windows also, but still not sure what to expect.
Btw, your [demo ](https://extensions.joomla.org/extension/responsive-images/) is n/a

**Comment by dgrammatiko** [comment]
@pl71 turns out that you're using absolute paths for your images. Responsive images (this plugin) assumes relative paths, as that is also the recommendation. There are options on every editor (either the latest tinyMCE that comes with J4 or the outdated jce) that allow you to do that. In simple terms you images should be like `<img src="/foo/bar.jpg">` instead of the current `<img src="scheme://www.example.com/foo/bar.jpg">`. I'll make a note on the documentation.

**Comment by pl71** [comment]
Hmm... So far so good. Relative paths are probably better, already switched on in JCE. I was also curious how these absolute paths would be handled in case I have to migrate.
Plugin is working - [test page](https://www.chernorizets.com/%D0%B4%D0%BE%D1%81%D1%82%D0%BE%D0%B9%D0%BD%D0%B8-%D1%87%D0%B5%D1%80%D0%BD%D0%BE%D1%80%D0%B8%D0%B7%D1%86%D0%B8/%D0%B1%D0%BB%D0%B0%D0%B3%D0%BE%D1%82%D0%B2%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D0%BB%D0%BD%D0%BE%D1%81%D1%82/%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%B0-%D0%BA%D0%B0%D1%83%D0%B7%D0%B0-%D0%B2-%D0%BF%D1%8A%D1%80%D0%B2%D0%B8%D1%8F-%D1%83%D1%87%D0%B5%D0%B1%D0%B5%D0%BD-%D0%B4%D0%B5%D0%BD) I see picture tag, but:
- [ ] Width and height attributes are changed. Is it normal? I want a small image beside the text with `width="240" height="180"`. This is what JCE inserted, but I could make it without JCE as well. Will try with tinyMCE also, but these attributes are fully valid, aren't they? `img` is inside `p` tag, but this is also valid. I want this image beside the text, not below. With plugin I receive full-width image with `width="1740" height="1302"` and text below it. Looking good, but not what I meant to.
- [ ] Not sure, but I suppose it fallbacks to jpg, despite created webp files. Still checking there.

**Comment by dgrammatiko** [comment]
>  Not sure, but I suppose it fallbacks to jpg, despite created webp files. Still checking there.

You can verify which image is in use by inspecting/selecting the image element and then in the console type `$0.currentSrc`
Eg
<img width="1233" alt="Screenshot 2022-10-18 at 21 55 21" src="https://user-images.githubusercontent.com/3889375/196531173-5052e6dd-64ed-499f-b855-bfb0138f5a5c.png">
<img width="1187" alt="Screenshot 2022-10-18 at 21 55 04" src="https://user-images.githubusercontent.com/3889375/196531201-7aa112d9-54ea-4a31-8a19-4668a6efb97d.png">

> Looking good, but not what I meant to.

The plugin creates multiple versions of the image with different dimensions and let the browser select the most appropriate for the current width of the browser. Anything that has to do with the styling can be achieved with CSS. The width and the height should not be used for the styling (size) of the image for that you need to use CSS. If you want to dive deeper this is a great resource: https://www.youtube.com/watch?v=YM3KszYmn58

**Comment by pl71** [comment]
@dgrammatiko thank you for the hint and link. I am aware of the importance of height and width attributes regarding [CLS](https://web.dev/optimize-cls/).
Anyway, JCE (again JCE, but TynyMCE also) is using them to instruct browsers about size, instead of placing some inline CSS code with every image. And the browser is performing as per these attributes obviously. I will appreciate it if the plugin is checking them and keep them intact. Presently output is different with plugin ON and OFF.

Core Joomla has a few options regarding image insertion, right? The intro image is a good idea, but again in full width and placed above the title. In a featured blog post this image looks like belonging to the previous post, what a design! I have to make an override.

[This](https://designwizard.com/blog/design-tips/blog-post-images/) is what I want to achieve, 30% (intro) image next to the text, left aligned, maybe all posts will look the same. Additional images - below the post. All images in WebP format with actual sizes as per size attributes.

**Comment by dgrammatiko** [comment]
> All images in WebP format with actual sizes as per size attributes.

This plugin is not just converting jpg/png to webp (or avif). It also generates source sets with different sizes, so maybe that's not what you're looking for?

> [This](https://designwizard.com/blog/design-tips/blog-post-images/) is what I want to achieve,

And the example you provided is also using CSS to achieve that (`style="width: 50%"`)
![Screenshot 2022-10-19 at 10 13 45](https://user-images.githubusercontent.com/3889375/196635688-6aec61a4-9cbc-4346-a8e9-1a3b564c74f2.png)


> I will appreciate it if the plugin is checking them and keep them intact. Presently output is different with plugin ON and OFF.

Sorry that won't happen as the width and height are the actual dimensions of the image so that the browser can correctly calculate the aspect ratio of the image in order to eliminate the CLS and I'm not willing to change that behaviour. FWIW the core Joomla is also doing that exact thing as well (I coded that as well)

**Comment by pl71** [comment]
Thank you, noted. Btw 4.2.0 is working well. Except UTF-8 encoding is broken - file names, alt tag... Following some [bits of advice](https://stackoverflow.com/questions/8218230/php-domdocument-loadhtml-not-encoding-utf-8-correctly), may I suggest a PR?
\libraries\Ttc\src\Freebies\Responsive\Helper.php
row 82:
` $docImage->loadHTML(mb_convert_encoding($image, 'HTML-ENTITIES', 'UTF-8'), LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);    `
