### ISSUE TITLE
Excluded Directories to include also all sub-folders

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#315]
Hi!
Do "Excluded Directories" include also all sub-folders or not?
I have a gallery (Phoca Gallery) which I want to exclude from processing.
All images are placed in subfolders of '/images/phocagallery' and their (subfolders) count varies.

**Comment by dgrammatiko** [comment]
The exclude directories are per folder no recursive functionality. I understand that in some cases is nice to define a top level folder and have everything in there as excluded but unfortunately it will introduce a big break on the current workflow.
It needs to wait till v5 (Aug 23)...

**Comment by dgrammatiko** [comment]
This is on the roadmap for the next version. Thanks for the idea
