### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#317]
> HTTP 500 Whoops, looks like something went wrong
> Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 50211396 bytes)
> .../libraries/Ttc/src/Freebies/Responsive/Thumbs.php (line 40)
> 

server and php.ini: "memory_limit = 128M"
Actually tried to convert a png file with relatively big dimensions: 3543 x 3543 pixels (bit depth 32) using GD.
With a disk size of less than 300K, this file is not suspicious.
So memory check is not correct or there is a memory leak.

**Comment by dgrammatiko** [comment]
That's interesting, the code for the memory checked was contributed by another person. If you could send me the image that causes this at d.grammatiko at gmail dot com I could try to debug it

**Comment by dgrammatiko** [comment]
Nevermind, fixed
