### ISSUE TITLE
Image sizes error

### ISSUE THREAD

**Issue by mediafoks** [ttc-freebies/plugin-responsive-images#318]
Joomla 4.2.4, Cassiopeia, Responsive Images v.4.2.0
The default value of Image sizes: 320, 768, 1200. When I change Image sizes to 480, 768, 1200, I get error: "Ttc\Freebies\Responsive\Helper::getSrcSets(): Return value must be of type string, null returned".

**Comment by dgrammatiko** [comment]
Try removing the spaces and not have a comma at the end

**Comment by mediafoks** [comment]
> Try removing the spaces and not have a comma at the end

Nothing has changed.
If you manually change **template**/html/layouts/joomla/html/image.php: `$breakpoints = [480, 768, 1200];` then it works.

**Comment by mediafoks** [comment]
Why doesn't it work through the admin panel?

**Comment by dgrammatiko** [comment]
@mediafoks sorry there was a type hint error, try [4.2.1](https://responsive-images.dgrammatiko.dev/dist/pkg_responsive_4.2.1.zip)

**Comment by mediafoks** [comment]
> @mediafoks sorry there was a type hint error, try [4.2.1](https://responsive-images.dgrammatiko.dev/dist/pkg_responsive_4.2.1.zip)

Everything is great. Thank you!

**Comment by dgrammatiko** [comment]
You're welcome, sorry for the glitch
