### ISSUE TITLE
Black background for PNG images.

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#323]
I'm experiencing also black background of png files, instead of transparent.
[Output ](https://chernorizets.com/?view=article&id=182) vs [image](https://chernorizets.com/images/english.png).
Presently investigating following [solution](https://stackoverflow.com/questions/2611852/imagecreatefrompng-makes-a-black-background-instead-of-transparent).

**Comment by dgrammatiko** [comment]
What version of the plugin are you using? The latest one should not have this problem

**Comment by pl71** [comment]
Yes, 4.2.1 is converting png well. I've cleared already generated images. Thank you.
