### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#324]
Sorry, I can't reopen issue #317, but still experiencing a memory leak.
Responsive Images Plugin is of the latest version 4.2.1, Joomla 4.2.4
White screen with 500 Internal Server Error.
This time in error_log:
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /.../libraries/Ttc/src/Freebies/Responsive/Thumbs.php on line 34`
Problematic jpeg image with dimensions: 3120 x 4160, bit depth 24.
It passes the initial memory check, but later you have a loop `for ($i = 0,...` and `\imagedestroy($sourceImage)` doesn't free memory nor `\gc_collect_cycles()`, so on the second iteration free memory is not enough.
Following [this](https://stackoverflow.com/questions/8520904/imagedestroy-does-not-to-free-memory) advice, I moved all logic inside a nested function, and strangely it worked like a charm.
This problem is commented also [here](https://stackoverflow.com/questions/32320212/why-gd-doesnt-release-memory-upon-imagedestroy).

**Comment by dgrammatiko** [comment]
Let me know if [this version](https://github.com/ttc-freebies/plugin-responsive-images/files/9945988/pkg_responsive_4.2.2.zip) fixes the bug

**Comment by pl71** [comment]
Yes, it is working well. Generated images were cleared and regenerated without errors. Thank you.

**Comment by dgrammatiko** [comment]
4.2.2 is released with the fix.

Thanks
