### ISSUE TITLE
Error message "Image too big to be processed"

### ISSUE THREAD

**Issue by nadjak77** [ttc-freebies/plugin-responsive-images#350]
Hi,
first of all: I really like your plugin. It works great.
But I have a problem on a website.
The image is a article image and I get the error message "Image too big to be processed" in the frontend.
https://scw-muenchen.de/?view=article&id=1701:2022-obb-kurzbahn-ingolstadt&catid=143

**Comment by dgrammatiko** [comment]
Hi,
you haven't provided enough details for the error so I will try some general tips here:
- check that you're using the latest version of the package
- re encode the image that fails with https://squoosh.app
- if your server provides both GD and Imagick graphic drivers try switching from the current one

In order for me even trying to replicate the issue I need your PHP version, the graphic driver version and the actual image that causes this

Thanks

**Comment by nadjak77** [comment]
Hi,
thanky for your reply.
I already used squoosh, but it did not solve the problem.
The version of the plugin is the latest from your website (4.2.2)
The php version is 8.0.26
Where can I find the graphic drivers?
I installed your plugin last friday and it worked for the existing images. At the weekend there was a new post, and there we have the error.
What further information do you need?
I sent you the link to the blogpost where the error can be found.
Thanks

**Comment by dgrammatiko** [comment]
Should be fixed with 4.2.6, if not feel free to reopen the issue
