### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by ch2856** [ttc-freebies/plugin-responsive-images#38]
Even if using 100% for quality, the image quality is very low.

**Comment by dgrammatiko** [comment]
Are you on joomla 3 or 4? Also what version of this plugin are you using, and what was the type of the input image (png, jpg)?

**Comment by ch2856** [comment]
Joomla 3.9.28, plugin v3.5.5 and .jpg, 100% quality, no scale up. 
I do have to mention that all my images are optimized in photoshop for web (50% quality) before uploaded.

Thanks

**Comment by dgrammatiko** [comment]
@ch2856 could you send me one image that gets really bad quality from the plugin to d.grammatiko [at] gmail.com?

Thanks

**Comment by dgrammatiko** [comment]
There is nothing wrong with the quality of the `produced images`. Fine-tuning images per instance will always be more efficient than a global setting, eg 75%. Also, this plugin is creating many images with different sizes so the efficiency is given and far superior to having 1 image fine-tuned to a size of some kb, as the browser will download only the best-fit image.
