### ISSUE TITLE
Error  json_decode(): Argument #1 ($json) must be of type string, stdClass given

### ISSUE THREAD

**Issue by RickR2H** [ttc-freebies/plugin-responsive-images#39]
Hey Dimitris,

Really nice plugin but I've got a small problem. After install I got an error.
It's on this line: https://github.com/ttc-freebies/plugin-responsive-images/blob/4.0.0/src/plugins/content/responsive/responsive.php#L76

Cheers!

**Comment by dgrammatiko** [comment]
Oh the json_decode() should be redundant as the params are already transformed to an object. Will check later on and release an update. Also, I need to finish the docs for the layouts...

**Comment by RickR2H** [comment]
> Oh the json_decode() should be redundant as the params are already transformed to an object. Will check later on and release an update. Also, I need to finish the docs for the layouts...

Great! Thanks for the work! I'll test as soon as there is a new version!

**Comment by dgrammatiko** [comment]
@RickR2H there's a new release and should fix the error. My fault I was testing with all the formats without checking what was supported.

Check https://responsive-images.dgrammatiko.dev/downloads/index.html

**Comment by dgrammatiko** [comment]
@RickR2H is the issue resolved with the latest release?

**Comment by RickR2H** [comment]
Have been on holiday and have not been able to test Wil try asap!

**Comment by RickR2H** [comment]
Hey Dimitris, Errors are gone but the srcset is not added to the article. The image is indeed found in the article, but not replaced. Maybe I'm doing something wrong...

I did a var_dump:

![image-4](https://user-images.githubusercontent.com/5610413/128635087-dccc2b60-6744-4ad7-875d-100173c12ed4.jpg)

I'm on a Windows machine / WAMPserver

**Comment by dgrammatiko** [comment]
> The image is indeed found in the article, but not replaced. Maybe I'm doing something wrong...

@RickR2H  was the image an intro or a fulltext image? If so there was a bug in the layout override (I assume you already downladed the overrides needed from here: https://responsive-images.dgrammatiko.dev/create-template-overrides/index.html

Let me know if that was the issue or there's something weird due to the OS (Windows)

**Comment by dgrammatiko** [comment]
This was fixed some time ago. @RickR2H if you're still getting errors please re open. Thanks
