### ISSUE TITLE
Call to a member function getAttribute() on null

### ISSUE THREAD

**Issue by johanvh83** [ttc-freebies/plugin-responsive-images#390]
I use Joomla 4.2.7. Yesterday I installed your plugin and so far haven't added any image.
When I load the frontpage I get many errors:

`libxml_use_internal_errors(true);    // it loads the content without adding enclosing html/body tags and also the doctype declaration    $docImage->LoadHTML(mb_convert_encoding($image, 'HTML-ENTITIES', 'UTF-8'), LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);    $src = $docImage->firstElementChild->getAttribute('src') ?? null;    if ($src) {      $paths = $this->getPaths($src);      $docImage->firstElementChild->setAttribute('src', ltrim($paths->path, '/'));    }`

`$img = '<img ' . ArrayHelper::toString($displayData) . '>';// Respect the plugin stateif (PluginHelper::isEnabled('content', 'responsive')) {  $img = (new ResponsiveHelper)->transformImage($img, $breakpoints);}echo $img;`

` if (empty($path)) {            return $layoutOutput;        }        ob_start();        include $path;        $layoutOutput .= ob_get_contents();        ob_end_clean();        return $layoutOutput;    }`
And many more...
When I disable your plugin, the frontpage works without any problem.

**Comment by dgrammatiko** [comment]
What is your php version?

**Comment by johanvh83** [comment]
I still run 7.4.30. Will update soon to 8.0.
This is the reason?

Op wo 1 feb. 2023 09:34 schreef Dimitris Grammatikogiannis <
***@***.***>:

**Comment by dgrammatiko** [comment]
@johanvh83 could you go to `YOU_DOMAIN/administrator/index.php?option=com_admin&view=sysinfo` click on the `Download As JSON` and send your server report to d.grammatiko@gmail.com

**Comment by johanvh83** [comment]
The URL you mentioned doesn't work on the server. What do you want me to do?


Op wo 1 feb. 2023 om 10:09 schreef Dimitris Grammatikogiannis <
***@***.***>:

**Comment by dgrammatiko** [comment]
You can go to the same page using the default navigation:
- Login to the backend ->
- main menu System -> 
- Information: System Information
- Click on the Download as JSON button on the toolbar

**Comment by johanvh83** [comment]
You mean the Joomla backend or my webhosting?

Op wo 1 feb. 2023 om 10:33 schreef Dimitris Grammatikogiannis <
***@***.***>:

**Comment by dgrammatiko** [comment]
It should be your Joomla backend

**Comment by dgrammatiko** [comment]
@johanvh83 please install this: 
[pkg_responsive_4.2.3-alpha.zip](https://github.com/ttc-freebies/plugin-responsive-images/files/10556062/pkg_responsive_4.2.3-alpha.zip)

And report back if you have any more problems.

Thanks

**Comment by johanvh83** [comment]
Hi,

I got in Joomla a message about an update of your plugin:
[image: Snap 2023-02-01 at 14.33.22.jpg]

I installed this update as it was the same version as your .zip file.

The error is gone, so my frontpage works but I see that a lot of <div>'s
with CSS styling are not in the correct position anymore.
No idea if it has to do with your plugin.

Anyway do you have any 'manual' how to use your plugin. I checked the
'documentation' but so far it's not clear.

Thanks in advance,

Johan

Op wo 1 feb. 2023 om 11:41 schreef Dimitris Grammatikogiannis <
***@***.***>:

**Comment by johanvh83** [comment]
Hi,

Apologies, please ignore the ' <div>'s with CSS styling ' message. Believe
some caching problems many.. It's resolved.

If I understand correctly, your plugin will automatically render 3 pictures
with different sizes and based on the viewers screen resolution (desktop,
tablet, mobile) they will be displayed. Correct?
Is this 'fully automated' when a new image is uploaded?

Kind regards,
Johan

Op wo 1 feb. 2023 om 11:41 schreef Dimitris Grammatikogiannis <
***@***.***>:

**Comment by dgrammatiko** [comment]
> Is this 'fully automated' when a new image is uploaded?

Yes, as long as you use the Joomla Media Manager then everything are automatic.

BTW using PHP 8.1 you have native support for AVIF, for earlier PHP versions you need imagick

**Comment by dgrammatiko** [comment]
Closing this PR since the issue was resolved with version 4.2.3. Thanks for reporting it
