### ISSUE TITLE
Version 4.2.3 error

### ISSUE THREAD

**Issue by mediafoks** [ttc-freebies/plugin-responsive-images#392]
After updating to version 4.2.3 blank white page and error "DOMDocument::loadHTML(): Argument #1 ($source) must not be empty".
Version 4.2.2 works great.
Joomla 4.2.7, PHP 8.1

**Comment by dgrammatiko** [comment]
@mediafoks could you try 4.2.4? Did the error go away?

Thanks

**Comment by mediafoks** [comment]
> could you try 4.2.4? Did the error go away?

Yes, it works great! Thank you!
