### ISSUE TITLE
Cant make module to work.

### ISSUE THREAD

**Issue by Darko-F** [ttc-freebies/plugin-responsive-images#421]
Hi, I have custom module and some media img in it.

Can someone help me what to write in plugin settings so  this images can be generated in web formats.

At the moment I have written in plugin component tab:
Component Name * - mod_custom
Component Views * - content
Component Database Columns * - Text

But this don't have any effect on images. Can someone help me, thanks.

**Comment by dgrammatiko** [comment]
Can you send me the module at: d.grammatiko at gmail.com

**Comment by Darko-F** [comment]
Never mind #159 This help me. Thank you for this plugin.
