### ISSUE TITLE
Is possible to get background images optimised?

### ISSUE THREAD

**Issue by Darko-F** [ttc-freebies/plugin-responsive-images#422]
Thank you all for this plugin it help me a lot for optimising my pictures.

I have question if is possible to optimise also pictures when are in background via CSS.

Like this in css: 
.banner {
    background-image: url(/images/headers/mypicture.jpg);
    background-repeat: no-repeat;
    height: 250px;
}

Thank you.

**Comment by dgrammatiko** [comment]
> I have question if is possible to optimise also pictures when are in background via CSS.

It is possible to assign the `background-image` within different media queries. This involves also some code to extract the urls from the `<source>` elements.

There's a much easier way though:

- Create a module layout override, ie `responsive-background.php`
- Set the Advanced -> Layout to the one you just created
- Copy the contents below into the override

<details>
<summary>Background image on the module custom</summary>

```php
<?php
defined('_JEXEC') || die;

use Joomla\CMS\Layout\LayoutHelper;

$modId = 'mod-custom' . $module->id;

$image = '';
if ($params->get('backgroundimage')) {
  $app->getDocument()->getWebAssetManager()->addInlineStyle(
    <<<CSS
#$modId {display: grid; height: 100% }
#$modId > picture,
#$modId img {grid-area: 1 / 1 / 1 / 1; width: 100%; height: auto;}
#$modId > .overlay {grid-area: 1 / 1 / 1 / 1; z-index: 1;}
CSS,
    ['name' => $modId]
  );
  $image = LayoutHelper::render('joomla.html.image', [
    'src' => $params->get('backgroundimage'),
    'alt' => '',
    'loading' => 'eager'
  ]);
}
?>

<div class="mod-custom custom banner-overlay" id="<?php echo $modId; ?>">
  <?= $image; ?>
  <div class="overlay">
    <?php echo $module->content; ?>
  </div>
</div>
```
</details>


The result: 
<img width="1493" alt="Screenshot 2023-03-16 at 13 03 37" src="https://user-images.githubusercontent.com/3889375/225613332-706b0e71-187e-4cb6-bef7-9248bcec8193.png">


@Darko-F let me know if this is helpful
