### ISSUE TITLE
Creates additional <body> tags inside the <article>.

### ISSUE THREAD

**Issue by slashdottom** [ttc-freebies/plugin-responsive-images#5]
Creates an additional `<body>` tag after the `<article>` tag and a closing `</body>` tag before the closing `</article>` tag, thereby creating 2 sets of 'body' tags in the document. See example html code below.

Tested with;

- Joomla 3.8.12
- Responsive content images 1.0.1
- YOOtheme Warp 7 template, Protostar template and Beez3 template.
- PHP 7.2

Example code;
`<!DOCTYPE HTML>`
`<html lang="en-gb" dir="ltr">`
`<head>`
`<meta charset="utf-8" />`
`<title>Test</title>`
`</head>`
`<body>`
`<section id="top-a">`
`<h2>Header title</h2>`
`</section>`
`<article>`
**`<body>`**
`<h1>Article title</h1>`
`<p><img src="/media/cached-resp-images/images/my-image@320.jpg" alt="image" srcset="/media/cached-resp-images/images/my-image@320.jpg 320w, /media/cached-resp-images/images/my-image@480.jpg 480w, /media/cached-resp-images/images/my-image@768.jpg 768w, /media/cached-resp-images/images/my-image@992.jpg 992w, /media/cached-resp-images/images/my-image@1200.jpg 1200w, "></p>`
**`</body>	`**
`</article>`
`<footer>`
`</footer>`
`</body>`
`</html>`

**Comment by dgrammatiko** [comment]
Let me know if https://github.com/ttc-freebies/plugin-responsive-images/pull/8 solves this issue

**Comment by slashdottom** [comment]
Although this fix does remove the additional opening and closing body tags, it introduces a new problem.

The first 5 characters of the line with the image are missing `<p><i` from the line `<p><img src="/media/cached-resp-images/ ...`

Because of this, the image source `my-image@320.jpg` is seen as an email address and the cloaking email JavaScript code is automatically inserted, followed by the remaining `srcset` details from the image tag.

**Comment by cn-tools** [comment]
should fixed with #9
