### ISSUE TITLE
Big Joomla site with thousands of pictures

### ISSUE THREAD

**Issue by mbauer1980** [ttc-freebies/plugin-responsive-images#515]
Hi Dimitris,

I want to use the responsive images plugin on a big site (Joomla 4) with thousands of articles and pictures (like 5000).
So generating the webp files might take a day or more on my server. I'm not really sure if it's a good idea to activate the process on my live site. Will it work to generate the files on my Joomla test site (that's a 1:1 duplicate of my live site) and later copy the files into the cached-resp-images folder of my live site having the same plugin settings on both sites? What do you think?

Thanks in advance

Michael

**Comment by dgrammatiko** [comment]
Hi Michael,

If you have access to the CLI on your server I think it would be preferable to do it with a CLI-script onsite. Also zipping the `cached-resp-images` images and unzipping it in the server should also work, but I haven't tried it with a recent version.

Let me know if the cli-script is something you're interested...

**Comment by mbauer1980** [comment]
Thanks for your reply. I guess my hoster allows me to run a cronjob with a php or perl script. That might work.
Maybe I could also try using a converter software and upload the files afterwards.
I'm just trying to let the plugin generate the files on my test site but I guess this will take like a day or more and there might be timeout bugs.

**Comment by dgrammatiko** [comment]
@mbauer1980 there's a CLI plugin: https://github.com/ttc-freebies/responsive-cli. You can download it from: https://github.com/ttc-freebies/responsive-cli/tree/main/packages.

Consider running it locally before installing and running it on your server (to get a feel of how long it will take).

**Comment by mbauer1980** [comment]
Hallo,

ich bin bis 15. Oktober 2023 im Urlaub.

Ihre Nachricht wird nicht weitergeleitet und erst nach meiner Rückkehr beantwortet.

Mit freundlichen Grüßen

Michael Bauer / TEXT-BAUER / hitchecker.de

**Comment by dgrammatiko** [comment]
A CLI plugin is now available to handle the generation of the thumbs in batch.
