### ISSUE TITLE
Slideshow module

### ISSUE THREAD

**Issue by xmkrejc33** [ttc-freebies/plugin-responsive-images#537]
Hello,
first of all, thank you for the great plugin. I could just ask you, if it is possible to use it with slideshow module as well. I am using DJ-ImageSlider Module, but I still can't get it to work together. Could you please give me an advise?

Many thanks

Martin

**Comment by dgrammatiko** [comment]
It should be fairly easy to adjust the layout of the module to use use the these images. There was an article even in [JCM](https://magazine.joomla.org/all-issues/february-2022/new-image-convention-to-help-developers) advising the developers to use the new way, I guess the author of your module didn't read/like it.

Anyways if you still struggle with it send me a copy at d.grammatiko at gmail dot com and I will fix it for you

Dimitris

**Comment by xmkrejc33** [comment]
Thank you very much for the link to the article. I updated the code according to it and now it works well. I think this link could be somewhere in the help or documentation. It is very helpful for newbie like me to know all context.
