### ISSUE TITLE
Error when displaying an image within an administrator module in the backend

### ISSUE THREAD

**Issue by torstenhoppe** [ttc-freebies/plugin-responsive-images#541]
Since an update to the current version of Joomla, there is a problem with the display of an image within an HTML-module (Administrator) in the backend. I get the information that the image is not available. If I deactivate the PlugIn, the display occurs without any problems.

Here is the code, that's generated without the plugin:

`
<img
    style="display: block; margin-left: auto; margin-right: auto;"
    src="../images/logoicon/logo.png"
    width="300" height="149" loading="lazy"
    data-path="local-images:/logoicon/logo.png">
`

And this how it looks like with activated plugin. It shows an oversized area but no image!

`
<picture class="responsive-image">
    
    <source
        type="image/webp"
        srcset="
            media/cached-resp-images/images/logoicon/logo_1200.webp?version=521e895a85b0f8940e4ebdc9d389ec32 1200w,
            media/cached-resp-images/images/logoicon/logo_768.webp?version=eadeeccad8bb631c183e87e20cec34c2 768w,
            media/cached-resp-images/images/logoicon/logo_320.webp?version=99e60e5b829ec18438fe27f70a86b9a9 320w">

    <source
        type="image/png"
        srcset="
            media/cached-resp-images/images/logoicon/logo_1200.png?version=626ddda17b12e7b29021e7546d03c6af 1200w,
            media/cached-resp-images/images/logoicon/logo_768.png?version=ce37dba83e93decd8c6df82a5ae906c1 768w,
            media/cached-resp-images/images/logoicon/logo_320.png?version=74c2414bb2ede8012972cb1284b1559a 320w">

    <img
        style="display: block; margin-left: auto; margin-right: auto;"
        src="../images/logoicon/logo.png"
        width="3448"
        height="1714"
        loading="lazy"
        data-path="local-images:/logoicon/logo.png">

</picture>
`

**Comment by dgrammatiko** [comment]
Interesting bug, could you share the layout of the module that produces this?

Thanks for reporting

**Comment by torstenhoppe** [comment]
> Interesting bug, could you share the layout of the module that produces this?
> 
> Thanks for reporting

Hi, sorry it tooks a while, here you can find some screenshots that descripts the problem completely.
![01_ThisIsHowItLooks](https://github.com/ttc-freebies/plugin-responsive-images/assets/78491005/c4762471-e09b-49f5-b846-6cc3538b3367)
![02_HereIsTheListAndPosition](https://github.com/ttc-freebies/plugin-responsive-images/assets/78491005/aa30eb70-8528-45e2-8a2f-6e965491da7b)
![03_EditorView](https://github.com/ttc-freebies/plugin-responsive-images/assets/78491005/a5594300-71f4-4ea2-8887-e13450f2dd69)
![04_TheBigSpaceViewWithoutTheImage](https://github.com/ttc-freebies/plugin-responsive-images/assets/78491005/d9836a78-7c90-432e-a4c7-827a1624dcfd)
Hope it help's to solve this issue.

**Comment by dgrammatiko** [comment]
Valid bug, I will release a new version once joomla v5 is live

**Comment by dgrammatiko** [comment]
4.2.7 should fix this problem.
If not please reopen this issue

Thanks

**Comment by torstenhoppe** [comment]
Sorry for my delay, but it won't work for me. When **Content - Responsive Images** is activated I can't enter my dashboard in the backend - the Error-Message is: 0 Class "Imagick" not found. And the same issue is frontend, the complete website is not shown.
