### ISSUE TITLE
Custom Modules

### ISSUE THREAD

**Issue by lushdomain** [ttc-freebies/plugin-responsive-images#545]
Hi,
The plugin does not seem to be working in custom modules.

I set the modules options to prepare content.

I checked in the db and the column name for the html content of the module is 'content' so I changed your default 'text' to content, but it makes no difference. The images in the custom module are still not processed by the plugin.

Would you please let me have an idea of what else to check.

Regards, Brendan

**Comment by dgrammatiko** [comment]
> The plugin does not seem to be working in custom modules.

How is the image used, is it an `<img>` tag in side the editor? Is it some css background? Hardcoded in the layout?

Could you provide the layout that you're using at d dot grammatiko at gmail dot com

**Comment by lushdomain** [comment]
email sent :)

**Comment by dgrammatiko** [comment]
This has been resolved elsewhere.
