### ISSUE TITLE
Doesn't work in com_tags

### ISSUE THREAD

**Issue by mediafoks** [ttc-freebies/plugin-responsive-images#597]
Menu item "List All Tags". In the template com_tags\tags\default_items.php I output the image in this way:

```
use Joomla\CMS\Layout\LayoutHelper;

<?php echo LayoutHelper::render(
	'joomla.html.image',
	[
	'src'   => $images->image_intro,
	'alt'   => $images->image_intro_alt,
	'class' => '',
	]
); ?>
```

It doesn't work.

In the plugin settings:
Component Name: com_tags
Component Views: tags
Component Database Columns: introtext,fulltext,text

and
Component Name: com_tags
Component Views: tag
Component Database Columns: introtext,fulltext,text
It doesn't work.

Tried outputting the image in different ways:

```
<?php echo LayoutHelper::render(
	'ttc.image',
	[
		'img' => '<img src="' . $images->image_intro . '" alt="' . $images->image_intro_alt . '"/>',
		'breakpoints' => [320, 768, 1200]
	]
); ?>
```

```
<?php echo HTMLHelper::_('image', $images->image_intro, $images->image_intro_alt, $imageOptions); ?>
```

Also not working. The image is rendered as normal, the plugin doesn't work.
Can you please tell me how to solve the problem?

**Comment by dgrammatiko** [comment]
I can't replicate it. Here's my setup **WITHOUT** changing anything on the plugin:

<img width="1725" alt="Screenshot 2024-02-12 at 11 04 30" src="https://github.com/ttc-freebies/plugin-responsive-images/assets/3889375/868a8ee1-6bf4-4988-b371-2987c1b5a651">

<img width="1719" alt="Screenshot 2024-02-12 at 11 04 42" src="https://github.com/ttc-freebies/plugin-responsive-images/assets/3889375/55528cd9-fbc1-4dbd-bc9b-99fc6b0218e3">


<img width="1618" alt="Screenshot 2024-02-12 at 11 04 14" src="https://github.com/ttc-freebies/plugin-responsive-images/assets/3889375/309ec6ab-e5b0-496c-b572-1f3d7a3951a1">

**Comment by mediafoks** [comment]
> I can't replicate it. Here's my setup **WITHOUT** changing anything on the plugin:

Figured it out. It turned out the tag image is too small 320x320px, so the plugin does not work. The issue can be closed.

**Comment by dgrammatiko** [comment]
Nice!
