### ISSUE TITLE
srcset ends with empty image-candidate string and sizes attribute must also be present.

### ISSUE THREAD

**Issue by slashdottom** [ttc-freebies/plugin-responsive-images#6]
W3 Validator highlights 2 issues;

1. Bad value for attribute srcset on element img: Ends with empty image-candidate string.
Seen in the example code below, there is a trailing comma and space that appears to be causing this error.

2. When the srcset attribute has any image candidate string with a width descriptor, the sizes attribute must also be present.
After removing the trailing comma and space from issue 1 above, the validator highlights that there is no sizes attribute.

Example code;
`<p><img src="/media/cached-resp-images/images/my-image@320.jpg" alt="image" srcset="/media/cached-resp-images/images/my-image@320.jpg 320w, /media/cached-resp-images/images/my-image@480.jpg 480w, /media/cached-resp-images/images/my-image@768.jpg 768w, /media/cached-resp-images/images/my-image@992.jpg 992w, /media/cached-resp-images/images/my-image@1200.jpg 1200w, "></p>`

Other than that, this plugin is great! BIG THANKS!

**Comment by dgrammatiko** [comment]
Let me know if validator is happy with https://github.com/ttc-freebies/plugin-responsive-images/pull/7

**Comment by slashdottom** [comment]
Unfortunately this fix removes all the commas with a space within the srcset, including the unwanted comma and space at the end of the srcset line.

It now appears like this;
`<p><img src="/media/cached-resp-images/images/my-image@320.jpg" alt="image" srcset="/media/cached-resp-images/images/my-image@320.jpg 320w/media/cached-resp-images/images/my-image@480.jpg 480w/media/cached-resp-images/images/my-image@768.jpg 768w/media/cached-resp-images/images/my-image@992.jpg 992w/media/cached-resp-images/images/my-image@1200.jpg 1200w"></p>`

**Comment by cn-tools** [comment]
should fixed with #9

**Comment by dgrammatiko** [comment]
Closing here as the pr from @cn-tools solves the problem nicely. Thanks again
