### ISSUE TITLE
Sppagebuilder

### ISSUE THREAD

**Issue by Sir-Seyop** [ttc-freebies/plugin-responsive-images#602]
Hello,
Can You explain how can i implement for SPpagebuilder 5?
TY

**Comment by dgrammatiko** [comment]
I have no idea what SPpagebuilder 5 is but there is documentation on the site

**Comment by 01Kuzma** [comment]
@Sir-Seyop , have you managed how to achieve it?
I've added:
Component Name -> com_sppagebuilder
Component Views - > article,content
Component Database Columns - >text

**Comment by dgrammatiko** [comment]
> I've added:
> Component Name -> com_sppagebuilder
> Component Views -> article,content
> Component Database Columns -> text

That should work

**Comment by 01Kuzma** [comment]
@dgrammatiko , thank you, but, hm, something is wrong :(
I did it like this:
img
but images are loaded without being processed.
Tried to debug the plugin here `plugins\content\responsive\` with simple `exit` statement, but it's also ignored...

**Comment by dgrammatiko** [comment]
External images will not be processed, the plugin works only on images stored on the server

**Comment by 01Kuzma** [comment]
It's a local images stored on my localhost, just the `laragon` creates URL with `.test`

**Comment by dgrammatiko** [comment]
> It's a local images stored on my localhost

Sorry didn't wrote that clearly: the plugin expects **relative** paths not **absolute**.

**Comment by 01Kuzma** [comment]
The same with relative path :(
![image](https://github.com/ttc-freebies/plugin-responsive-images/assets/569504/6f253f62-cef2-4487-a3c8-133291bbcaf5)

**Comment by dgrammatiko** [comment]
What's the size of the image?

**Comment by 01Kuzma** [comment]
The `png` is `200x200`
![image](https://github.com/ttc-freebies/plugin-responsive-images/assets/569504/0a6590a5-561b-4881-8bf3-c41514167966)

Also, there is another `jpg` which loads with relative path from the template folder: `/templates/shaper_helixultimate/images/page_img/contacts/test.jpg` -> it's size is `610x687`

**Comment by dgrammatiko** [comment]
The image is skipped because it's too small (200x200)...

**Comment by dgrammatiko** [comment]
> Also, there is another jpg which loads with relative path from the template folder:

There's a problem with that path, it's only used on legacy templates. The plugin will never support the old templates (ie the ones that don't allow child templates).

You could probably edit the layout that echoes this image and follow the docs to allow responsive images to replace the tag: https://responsive-images.dgrammatiko.dev/documentation/layouts/

**Comment by 01Kuzma** [comment]
hm, I have bigger:

**Comment by dgrammatiko** [comment]
How is that image inserted? Was it part of the editor (ie tinyMCE) or using a field (ie like the into text image on the Joomla article edit form)?

The plugin **will ONLY** replace images that belong to an editor column in the database. For the field inserted images you need to edit the layout override and follow the docs: https://responsive-images.dgrammatiko.dev/documentation/layouts/

**Comment by 01Kuzma** [comment]
Builder uses it's own Add-Ons, or fields for input. How it's processed internally, honestly, I don't know.
![image](https://github.com/ttc-freebies/plugin-responsive-images/assets/569504/63e8c5f7-fdb9-4c63-9595-e65cd8bebdf0)

So, it seems, that it won't work with it

**Comment by dgrammatiko** [comment]
Probably they're using layouts for each field. Even if that's not the case they probably using layouts for their pages so should be possible

**Comment by 01Kuzma** [comment]
Understood, thank you!
