### ISSUE TITLE
Articles and Categories: Images Intro and Fulltext

### ISSUE THREAD

**Issue by netzalben** [ttc-freebies/plugin-responsive-images#604]
Hello,
Joomla 5:
Database Table "content" column "images" has no `<img>`-Tag. 
How can "image_intro" and "image_fulltext" be made responsive?
Thanks!

**Comment by dgrammatiko** [comment]
Database parts are only for editor fields content. For the other ones, ie media field, the image is rendered through a layout named image and it’s covered ootb. Do you have some override/template that is messing the default rendering?

**Comment by netzalben** [comment]
I am still examining, whether to change from WordPress to Joomla!. Seems, I misunderstood the labeling of the third parameter in the setup.
I shall write an own template. I can enter the fulltext-image into the content-area. The intro-image is usually small, so the effect of having it responsive will not be enormous.
I think, I can live with this.
Again, many thanks.
