### ISSUE TITLE
GD library is required for manipulation of images.

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#609]
Nice to have: A code that doesn't throw such an error if no graphics driver is loaded.
`throw new \RuntimeException('GD library is required for manipulation of images.');`
So, you can just silently do nothing.
And somewhere in the setting to inform the administrator that this plugin can't work properly.
My test site went down, but it could be a real site due to some technical issues with the server's drivers.

**Comment by dgrammatiko** [comment]
Without GD also the media manager is not working and also the core plugin resize throws the same error! Joomla if I’m not wrong has a hard dependency on GD. 
anyways something that would consider for a later release.

thanks
