### ISSUE TITLE
Resized images should be handled properly.

### ISSUE THREAD

**Issue by pl71** [ttc-freebies/plugin-responsive-images#611]
TinyMCE and JCE can resize images by adding `width` and `height` attributes to the HTML code.
(The actual image is not resized, you know, only attributes to <img> tag are added).
Unfortunately, this plugin ignores any values written there and directly replaces them with new ones.
Doing so we end with a different look of the page.

**Example:**
I uploaded an image with dimensions 1536x2048px and I resized it in an article (using JCE) to new dimensions: 273x364px.
I would like this image to be placed next to the text, right aligned.
Probably JCE Pro could resize the image file and use a smaller version, but in my case, only the `width `and `height `attributes were amended. Do not blame JCE, this is possible with TinyMCE also.
(EDIT: Yes, I know, I should upload a new file version 273px wide, this was not done).

So, what does the plugin do with my image? It ended with HTML like that:
`.../media/cached-resp-images/images/path-to-file/image-file_1200.webp?version=9be9ff46da4b28f8ee0b883347438828"
`
and
`<img decoding="async" src="/images/path-to-file/image-file.jpg" alt="" width="1536" height="2048" style="float: right;" loading="lazy" data-path="local-images:/path-to-file/image-file.jpg">
`
Obviously, with this coding the image occupied much more space on the screen, the text went down, etc. Moreover, I don't need such a resolution in case the image has to be only 273px wide. So the plunging respects only the file properties, not any added <img> attributes.

**Comment by dgrammatiko** [comment]
Couple of observations:
- the width and height of an image tag is used by the browser to define the aspect ratio of the image before the image has been downloaded from the server. These values should not be different from the actual aspect ratio and definitely not used as values that control the presentation of the image, for that use either the style attribute or even better a css class.
- my advice is that nobody should install and use jce in Joomla 4/5…

**Comment by pl71** [comment]
Thank you for your prompt answer.
1. Width and height `img ` attributes are added by TinyMCE, as well, and so far I don't know any other (and free of charge, though not compulsory) way to adjust images in articles. How to do a real resize of the files on the fly with a WYSIWYG editor?
2. Well noted, but could you be more specific? What is wrong with JCE?

**Comment by dgrammatiko** [comment]
> How to do a real resize of the files on the fly with a WYSIWYG editor?

this plugin with tinyMCE and the default media manager is doing all the resizes on image upload by default. You don’t need anything more than Joomla itself…

Ok, maybe I didn’t explained myself clearly, so let me retry. This plugin is about serving different image sizes depending on the viewport (desktop/tablet/phone), thus the reponsive name. The images get their own sizes depending on the original image aspect ratio. The final image size is depending on the size of the width of the browser. You should  NOT try to insert false numbers in the width/height attributes! Use either a css class to do the sizing (although if you want to anchor these values with particular values then the whole responsive effect is largely ignored)

**Comment by pl71** [comment]
> You should NOT try to insert false numbers in the width/height attributes!

But they are added by TinyMCE when I try to resize an image by corner handles. I do not amend the generated code manually.
I understand this is not the best approach for a Joomla editor, but I'm not the only one using this.
Otherwise, I have to upload every time a new resized image when I edit an article adding text, images, adjusting spaces, placement, etc.

ADD: In my opinion, this plugin should check actual image dimensions AND desired image dimensions within `img`. 
From [W3 school](https://www.w3schools.com/tags/att_img_width.asp):

> Tip: Downsizing a large image with the height and width attributes forces a user to download the large image (even if it looks small on the page). To avoid this, rescale the image with a program before using it on a page.

But it is a tip only, not a rule. In fact, the plugin rescales images and should use an appropriate scale when substituting HTML code. With appropriate I mean the next available size higher than `width` attribute in `img`, taking into account viewport (probably the place allocated for that element by browser). Looks like this should be done by JS.

**Comment by dgrammatiko** [comment]
Maybe understanding how images actually work in browsers is more helpful here. I would suggest you watch this video from [Jen Simmons](https://www.youtube.com/watch?v=4-d_SoCHeWE). The video actually explains why this plugin works the way it does.

Thanks

**Comment by pl71** [comment]
The video is nice. TinyMCE also [nicely resizes](https://www.tiny.cloud/blog/resize-image/) using HTML code. At least the version shipped with J 5.0.3.  Maybe TimyMCE 7.0 will not do that, who knows...  We are [waiting for a Joomla update](https://github.com/joomla/joomla-cms/issues/43110). JCE is used by many, you can ignore that fact. Until then I've commented out two lines of code:
` // $image->tag = preg_replace('(height="(.*?)")', 'height="' . $srcSets->base->height . '"', $image->tag);`
and
` // $image->tag = preg_replace('(width="(.*?)")', 'width="' . $srcSets->base->width . '"', $image->tag);`
Which will keep the existing `width `and `height `attributes. I have many images inside articles resized with WYSIWYG editors.
By the way, I see no reason to replace these attributes if they exist and you assume they are equal to the image file properties.
