### ISSUE TITLE
Native Joomla 5.x support?

### ISSUE THREAD

**Issue by 01Kuzma** [ttc-freebies/plugin-responsive-images#614]
Hi,
Just wondering, will the plugin support the Joomla 5.x without the backward compatibility plugin?
Thank you!

**Comment by dgrammatiko** [comment]
> Just wondering, will the plugin support the Joomla 5.x without the backward compatibility plugin?

Why do you think this needs the backwards compatibility plugin? The code is native Joomla 4 which essentially is the same as Joomla 5, it never used Joomla 3 APIs thus it's actually native J5 code.

**Comment by 01Kuzma** [comment]
That's great, I haven't checked it before so asked in advance.
Thank you!
