### ISSUE TITLE
AVIF Format in GD ?

### ISSUE THREAD

**Issue by conseilgouz** [ttc-freebies/plugin-responsive-images#616]
Hi Dimitris,

After a quick look in your sources, in lib_ttc_4.2.7/src/Freebies/Responsive/Thumbs.php, I think there's a mistake on AVIF conversion while using GD : 

Line 68 shows 
        if ($options->enableAVIF && \imagewebp($destImage, JPATH_ROOT . '/' . $fileSrc . '.avif', $options->qualityAVIF)) {

when it should be 

        if ($options->enableAVIF && \imageavif($destImage, JPATH_ROOT . '/' . $fileSrc . '.avif', $options->qualityAVIF)) {

See https://www.php.net/manual/en/function.imageavif.php

Pascal

**Comment by dgrammatiko** [comment]
Good catch

**Comment by dgrammatiko** [comment]
Fixed with https://github.com/ttc-freebies/plugin-responsive-images/commit/efc8099bed9557414de80de0d526bf05fcbd17c8
