### ISSUE TITLE
Images in content of RSS feed 

### ISSUE THREAD

**Issue by wderuijter** [ttc-freebies/plugin-responsive-images#634]
Hi @dgrammatiko 
I've got an RSS feed I'm using: https://www.soetkees.nl/nieuws?format=feed&type=rss
In which the description of the items can show something like this:

```
<description><![CDATA[<p><picture class="responsive-image"><source type="image/webp" srcset="/media/cached-resp-images/images/soetkees-homepage_1200.webp?version=a01eddf85dfed49c1c433112e0da1d6d 1200w, /media/cached-resp-images/images/soetkees-homepage_768.webp?version=8eb19fe357b4bf0f9d7053aa62399f96 768w, /media/cached-resp-images/images/soetkees-homepage_320.webp?version=61628a46ca1e8791d5ba1ab5ffee9bf5 320w"><source type="image/jpeg" srcset="/media/cached-resp-images/images/soetkees-homepage_1200.jpg?version=286347e618822dc081586cd65cd2faad 1200w, /media/cached-resp-images/images/soetkees-homepage_768.jpg?version=7a7f3ff60ed6b4a7c7af248b4fa54122 768w, /media/cached-resp-images/images/soetkees-homepage_320.jpg?version=2755c3c5a6538f6bae8d5a0c98069b02 320w"><img width="3968" height="2230" src="https://www.soetkees.nl//images/soetkees-homepage.jpg" alt="" decoding="async" loading="lazy"></picture></p><h2>Dat moeten we vieren! </h2>
<p>De fonkelnieuwe website van Soetkees is, na vele maanden bloed, zweet en tranen, eíndelijk online! Joehoe! Dat moet natuurlijk gevierd worden. Achter de schermen hebben we hier zo lang aan gewerkt. En nu is het eindelijk klaar, af, finito. Daarom maakt iedereen die mijn website bezoekt de komende maand kans op 3 toffe prijzen. Elke week verstop ik een cadeautje op de website. Kan jij 'm vinden?</p>
]]></description>
``` 
Could it be this content generated by the responsive images plugin and if so, is it intended to do this for the Joomla RSS feeds as well?

**Comment by dgrammatiko** [comment]
Hi @wderuijter 

You're right the tag is coming from the plugin. That said according to the official w3c validator the feed is [valid](https://validator.w3.org/feed/check.cgi?url=https%3A//www.soetkees.nl/nieuws%3Fformat%3Dfeed%26type%3Drss)

That said there might be older readers that would not parse correctly the `<picture>` tag, ie: https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fwww.soetkees.nl%2Fnieuws%3Fformat%3Dfeed%26type%3Drss

If this is a major problem I could add a simple check for RSS documents and skip the picture tag creation.


Let me know if the feed is somehow problematic for any of your users


Regards

Dimitris

**Comment by wderuijter** [comment]
Thanks @dgrammatiko, thanks for the explanation! It is indeed valid and non problematic for me and it probably also isn't for my users.
